package com.konakart.app;

/**
 *  The KonaKart Custom Engine - AddCustomDataToSession - Generated by CreateKKCustomEng
 */
// edit for VERITA-196
@SuppressWarnings("all")
public class AddCustomDataToSession
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public AddCustomDataToSession(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public void addCustomDataToSession(String sessionId, String data, int position) throws KKException
     {
         kkEng.addCustomDataToSession(sessionId, data, position);
     }
}
