package com.konakart.app;

import com.konakart.appif.*;
// edit for verita 137
/**
 *  The KonaKart Custom Engine - DeleteWishListWithOptions - Generated by CreateKKCustomEng
 */
@SuppressWarnings("all")
public class DeleteWishListWithOptions
{
    KKEng kkEng = null;

    /**
     * Constructor
     */
     public DeleteWishListWithOptions(KKEng _kkEng)
     {
         kkEng = _kkEng;
     }

     public void deleteWishListWithOptions(String sessionId, int wishListId, AddToWishListOptionsIf options) throws KKException
     {
         kkEng.deleteWishListWithOptions(sessionId, wishListId, options);
     }
}
